apps/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('email-verification/<email>/', views.email_verification, name='email-verification'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='reset-password'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('apps.catalog.urls', namespace='catalog')),
    path('posts/', include('apps.posts.urls', namespace='posts')),
    path('users/', include('apps.users.urls', namespace='users')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.hashers import make_password
from django.db import models
from django.contrib.auth.models import UserManager
from django.utils.translation import gettext_lazy as _

# Create your models here.


class CustomUserManager(UserManager):
    def _create_user(self, email, password, **extra_fields):
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField(_("email address"), unique=True)
    avatar = models.ImageField(upload_to="users", null=True, blank=True)
    phone = models.CharField(max_length=255, null=True, blank=True)
    country = models.CharField(max_length=255, null=True, blank=True)
    is_email_verified = models.BooleanField(
        default=False, verbose_name=_("Email подтверждён")
    )

    objects = CustomUserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _("Пользователь")
        verbose_name_plural = _("Пользователи")

apps/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ("email", "password1", "password2")


class ResetPasswordForm(forms.Form):
    email = forms.EmailField()

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if not get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Такого пользователя не существует")
        return email

apps/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.hashers import make_password
from django.core.mail import send_mail
from django.http import HttpRequest
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import generic

import random
from string import ascii_letters, digits

from .forms import ResetPasswordForm, UserCreationForm
# Create your views here.


class RegisterView(generic.CreateView):
    model = get_user_model()
    form_class = UserCreationForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    # def form_valid(self, form):
    # """ Send email for verification """
    #     email = form.cleaned_data.get('email')
    #     encoded_email = urlsafe_base64_encode(bytes(email, 'utf-8'))
    #     url = reverse('users:email-verification', kwargs={'email': encoded_email})
    #     full_url = f'{self.request.scheme}://{self.request.get_host()}{url}'
    #     send_mail(
    #         'Подтверждение электронной почты',
    #         f'Для подтверждения адреса электронной почты перейдите по ссылке: {full_url}',
    #         None,
    #         recipient_list=[email],
    #     )
    #     return super().form_valid(form)


def email_verification(request: HttpRequest, email):
    email = urlsafe_base64_decode(email).decode('utf-8')
    user = get_user_model().objects.get(email=email)
    if not user.is_email_verified:
        user.is_email_verified = True
        user.save()
    return redirect('users:login')


class ResetPasswordView(generic.FormView):
    template_name = 'users/reset-password.html'
    form_class = ResetPasswordForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        email = form.cleaned_data.get('email')
        new_password = "".join(random.sample(digits + ascii_letters, 8))
        user = get_user_model().objects.get(email=email)
        user.password = make_password(new_password)
        user.save()
        send_mail(
            'Восстановление пароля',
            f'Ваш пароль был сброшен. Ваш новый пароль {new_password}',
            None,
            recipient_list=[email],
        )
        return super().form_valid(form)

apps/users/templates/users/login.html
{% extends 'catalog/base.html' %}
{% load widget_tweaks %}

{% block content %}

    <div class="container text-center d-flex justify-content-center">
        <div class="row">
            <div class="col-12">
                <form method="post">
                    {% csrf_token %}
                    <label for="{{ form.username.id_for_label }}">Адрес электронной почты</label>
                    {% render_field form.username type="email" class="form-control" %}
                    {% for error in form.username.errors %}<div class="alert alert-danger">{{ error }}</div>{% endfor %}

                    <label for="{{ form.password.id_for_label }}">Пароль</label>
                    {% render_field form.password type="password" class="form-control" %}
                    {% for error in form.password.errors %}<div class="alert alert-danger">{{ error }}</div>{% endfor %}

                    <br />

                    <a href="{% url 'users:reset-password' %}" class="btn btn-dark">Забыли пароль?</a>
                    <button type="submit" class="btn btn-warning">Войти</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

apps/users/templates/users/register.html
{% extends 'catalog/base.html' %}
{% load widget_tweaks %}

{% block content %}

    <div class="container text-center d-flex justify-content-center">
        <div class="row">
            <div class="col-12">
                <form method="post" action="{% url 'users:register' %}">
                    {% csrf_token %}
                    <label for="{{ form.email.id_for_label }}">Адрес электронной почты</label>
                    {% render_field form.email type="email" class="form-control" %}
                    {% for error in form.email.errors %}<div class="alert alert-danger">{{ error }}</div>{% endfor %}

                    <label for="{{ form.password1.id_for_label }}">Пароль</label>
                    {% render_field form.password1 type="password" class="form-control" %}
                    {% for error in form.password1.errors %}<div class="alert alert-danger">{{ error }}</div>{% endfor %}

                    <label for="{{ form.password2.id_for_label }}">Повторите пароль</label>
                    {% render_field form.password2 type="password" class="form-control" %}
                    {% for error in form.password2.errors %}<div class="alert alert-danger">{{ error }}</div>{% endfor %}

                    <br />
                    <button type="submit" class="btn btn-warning" id="submit-button">Зарегистрироваться</button>
                </form>
            </div>
        </div>
    </div>
    <script>
        document.getElementById('submit-button').addEventListener('click', function() {
            alert('После успешной регистрации на вашу почту будет отправлено письмо для подтверждения регистрации. Не забудьте проверить папку "Спам".');
        });
    </script>

{% endblock content %}

apps/users/templates/users/reset-password.html
{% extends 'catalog/base.html' %}
{% load widget_tweaks %}

{% block content %}
    <div class="container text-center d-flex justify-content-center">
        <div class="row">
            <div class="col-12">
                <form method="post">
                    {% csrf_token %}
                    <label for="{{ form.email.id_for_label }}">Адрес электронной почты</label>
                    {% render_field form.email type="email" class="form-control" %}
                    {% for error in form.email.errors %}<div class="alert alert-danger">{{ error }}</div>{% endfor %}
                    <br>
                    <button type="submit" class="btn btn-warning">Отправить</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}