apps/catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views


app_name = 'catalog'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='product_list'),

    path('categories/', views.CategoryListView.as_view(), name='category_list'),
    
    path('product/create/', views.ProductCreateView.as_view(), name='product_form'),
    path('product/<int:pk>/', cache_page(60)(views.ProductDetailView.as_view()), name='product_detail'),
    path('product/update/<int:pk>/', views.ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', views.ProductDeleteView.as_view(), name='product_delete'),

    path('product/<int:product_pk>/versions/', views.VersionListView.as_view(), name='version_list'),
    path('product/<int:product_pk>/versions/create/', views.VersionCreateView.as_view(), name='version_form'),
    path('versions/delete/<int:pk>/', views.VersionDeleteView.as_view(), name='version_delete'),
    path('versions/toggle_current/<int:pk>/', views.toggle_current_version, name='version_toggle'),

    path('feedback/', views.FeedbackView.as_view(), name='feedback'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('apps.catalog.urls', namespace='catalog')),
    path('posts/', include('apps.posts.urls', namespace='posts')),
    path('users/', include('apps.users.urls', namespace='users')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/catalog/models/basemodel.py
from django.db import models


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

apps/catalog/models/category.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from .basemodel import BaseModel


class Category(BaseModel):
    name = models.CharField(max_length=255, verbose_name=_('Название'))
    description = models.TextField(blank=True, verbose_name=_('Описание'))

    class Meta:
        verbose_name = _('Категория')
        verbose_name_plural = _('Категории')

    def __str__(self):
        return self.name

apps/catalog/models/censor.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from .basemodel import BaseModel


class Censor(BaseModel):
    word = models.CharField(max_length=255, verbose_name=_('Слово'))

    def __str__(self):
        return self.word

    class Meta:
        verbose_name = _('Цензура')
        verbose_name_plural = _('Цензура')

apps/catalog/models/product.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from .basemodel import BaseModel


class Product(BaseModel):
    user = models.ForeignKey('users.User', on_delete=models.CASCADE, verbose_name=_('Пользователь'), related_name='products')
    name = models.CharField(max_length=255, verbose_name=_('Название'))
    description = models.TextField(blank=True, verbose_name=_('Описание'))
    image = models.ImageField(upload_to='products/', blank=True, null=True, verbose_name=_('Изображение'))
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name=_('Категория'))
    price = models.FloatField(verbose_name=_('Цена'))
    is_published = models.BooleanField(default=False, verbose_name=_('Опубликовано'))

    class Meta:
        verbose_name = _('Продукт')
        verbose_name_plural = _('Продукты')
        permissions = [
            ("can_change_published", "Can change is_published status"),
            ("can_change_description", "Can change description"),
            ("can_change_category", "Can change category"),
        ]

    def __str__(self):
        return self.name

apps/catalog/models/version.py
from django.db import models
from django.db.models.signals import pre_save, post_delete
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _

from .basemodel import BaseModel


class Version(BaseModel):
    name = models.CharField(max_length=255, verbose_name=_('Название версии'))
    number = models.IntegerField(unique=True, verbose_name=_('Номер версии'))
    is_current = models.BooleanField(default=True, verbose_name=_('Текущая версия'))
    product = models.ForeignKey('Product', on_delete=models.CASCADE, verbose_name=_('Продукт'), related_name='versions')

    class Meta:
        verbose_name = _('Версия продукта')
        verbose_name_plural = _('Версии продукта')
        ordering = ['number']

    def __str__(self):
        return f'{self.number}. {self.name} ({self.is_current})'


@receiver(pre_save, sender=Version)
def pre_save_version(sender, instance, **kwargs):
    Version.objects.filter(product=instance.product, is_current=True).update(is_current=False)


@receiver(post_delete, sender=Version)
def post_delete_version(sender, instance, **kwargs):
    if instance.is_current:
        previous_versions = Version.objects.filter(product__pk=instance.product.pk)
        if previous_versions.exists():
            previous_version = previous_versions.latest('number')
            previous_version.is_current = True
            previous_version.save()

apps/catalog/forms.py
from django import forms
from .models import Product, Censor


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ['name', 'description', 'image', 'category', 'price', 'is_published']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['is_published'].widget.attrs['hidden'] = True
        self.fields['is_published'].label = ''

    def clean_name(self):
        name = self.cleaned_data['name'].lower()
        stop_words = []
        for censured_word in Censor.objects.values_list('word', flat=True):
            if censured_word.lower() in name:
                stop_words.append(censured_word)
        if stop_words:
            raise forms.ValidationError(f'Содержутся запрещенные слова: {', '.join(stop_words)}')
        return name

    def clean_description(self):
        description = self.cleaned_data['description'].lower()
        stop_words = []
        for censured_word in Censor.objects.values_list('word', flat=True):
            if censured_word.lower() in description:
                stop_words.append(censured_word)
        if stop_words:
            raise forms.ValidationError(f'Содержутся запрещенные слова: {', '.join(stop_words)}')
        return description


class ModeratorProductForm(ProductForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].disabled = True
        self.fields['image'].disabled = True
        self.fields['price'].disabled = True
        self.fields['is_published'].widget.attrs['hidden'] = False
        self.fields['is_published'].label = 'Опубликован:'

apps/catalog/views.py
from django.views import generic
from django.urls import reverse_lazy
from django.shortcuts import redirect, render
# Create your views here.

from .forms import ProductForm
from .models import Product, Version


class ProductListView(generic.ListView):
    model = Product


class ProductCreateView(generic.CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')


class ProductDetailView(generic.DetailView):
    model = Product


class ProductDeleteView(generic.DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:product_list')


class FeedbackView(generic.View):

    def get(self, request):
        return render(request, 'catalog/feedback.html')

    def post(self, request):
        return redirect('catalog:product_list')

apps/catalog/views/categories.py
from django.views import generic

from apps.catalog.models import Category
from apps.catalog.services import get_cached_list_categories


class CategoryListView(generic.ListView):
    model = Category
    queryset = get_cached_list_categories()

apps/catalog/views/feedback.py
from django.views import generic
from django.shortcuts import redirect, render
# Create your views here.


class FeedbackView(generic.View):

    def get(self, request):
        return render(request, 'catalog/feedback.html')

    def post(self, request):
        return redirect('catalog:product_list')

apps/catalog/views/product.py
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

from apps.catalog.models import Product
from apps.catalog.forms import ModeratorProductForm, ProductForm
from apps.users.permissions import EmailVerifiedRequiredMixin


class ProductListView(generic.ListView):
    model = Product


class ProductCreateView(LoginRequiredMixin, EmailVerifiedRequiredMixin, generic.CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')
    login_url = reverse_lazy('users:login')

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        return super().form_valid(form)


class ProductDetailView(LoginRequiredMixin, EmailVerifiedRequiredMixin, generic.DetailView):
    model = Product


class ProductUpdateView(LoginRequiredMixin, EmailVerifiedRequiredMixin, generic.UpdateView):
    model = Product
    success_url = reverse_lazy('catalog:product_list')

    def get_form_class(self):
        if self.request.user.groups.filter(name='moderator').exists():
            return ModeratorProductForm
        return ProductForm


class ProductDeleteView(LoginRequiredMixin, EmailVerifiedRequiredMixin, generic.DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:product_list')

apps/catalog/views/version.py
from django.views import generic
from django.urls import reverse
from django.shortcuts import redirect

from apps.catalog.models import Product, Version


class VersionListView(generic.ListView):
    model = Version

    def get_queryset(self):
        return Version.objects.filter(product__pk=self.kwargs['product_pk'])

    def get_context_data(self, **kwargs):
        return super().get_context_data(product_pk=self.kwargs['product_pk'], **kwargs)


class VersionCreateView(generic.CreateView):
    model = Version
    fields = ('name', 'number', 'is_current')

    def form_valid(self, form):
        form.instance.product = Product.objects.get(pk=self.kwargs['product_pk'])
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('catalog:version_list', kwargs={'product_pk': self.kwargs['product_pk']})


class VersionDeleteView(generic.DeleteView):
    model = Version

    def get_success_url(self):
        return reverse('catalog:version_list', kwargs={'product_pk': self.object.product.pk})


def toggle_current_version(request, pk):
    version = Version.objects.get(pk=pk)
    version.is_current = not version.is_current
    version.save()
    return redirect('catalog:version_list', product_pk=version.product.pk)

apps/catalog/templates/catalog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <script defer src="{% static 'js/htmx.min.js' %}"></script>
    <script defer src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <title>Shoppify</title>
  </head>
  <body data-bs-theme="dark" id="body" hx-boost="true">
    {% include "catalog/includes/header.html" %}
    {% block content %}

    {% endblock content %}
  </body>
</html>

apps/catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}

{% block content %}

    <div class="container">
        <h1>Категории</h1>
        <div class="row">
            {% for category in category_list %}
                <ul>
                    <li>{{ category }}</li>
                </ul>
            {% endfor %}
        </div>
    </div>

{% endblock content %}

apps/catalog/templates/catalog/feedback.html
{% extends 'catalog/base.html' %}
{% block content %}
  <form method="post">
    {% csrf_token %}
    <input type="text" name="name" /><br />
    <input type="email" name="email" /><br />
    <textarea name="message"></textarea> <br />
    <button type="submit">Отправить</button>
  </form>
{% endblock content %}

apps/catalog/templates/catalog/index.html
{% extends "catalog/base.html" %}

{% block content %}
  <h1>Каталог</h1>
  <div class="row w-100">
    {% for product in product_list %}
      {% include 'catalog/includes/card.html' with product=product %}
    {% endfor %}
  </div>
{% endblock content %}

apps/catalog/templates/catalog/product.html
{% extends "catalog/base.html" %}

{% block content %}

    <h1>{{ product }}</h1>
    <img src="{{ product.image.url }}" alt="" width="200" height="300" />
    <p>{{ product.description }}</p>
    <p>{{ product.price|floatformat }}р</p>
    <a href="{% url 'catalog:index' %}" class="btn btn-warning">Назад</a>

{% endblock content %}

apps/catalog/templates/catalog/product_detail.html
{% extends "catalog/base.html" %}
{% load custom_tags %}

{% block content %}

    <div class="container">
        <h1>{{ product }}</h1>
        <img src="{{ product|img_url }}" alt="" width="200" height="300" />
        <p>{{ product.description }}</p>
        <p>{{ product.price|floatformat }}р</p>

        <a href="{% url 'catalog:version_list' product_pk=product.pk %}"
           class="btn btn-warning">Список версий</a>
        <br>
        <br>
        <a href="{% url 'catalog:product_list' %}" class="btn btn-warning">Назад</a>
    </div>

{% endblock content %}

apps/catalog/templates/catalog/product_form.html
{% extends "catalog/base.html" %}
{% load widget_tweaks %}
{% block content %}

  <div class="container text-center mt-5">
    <h1>Добавить продукт</h1>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <label for="{{ form.category.id_for_label }}">Категория:</label>
      {% render_field form.category type="text" class="form-select" %}
      <br>
      <label for="{{ form.name.id_for_label }}">Название:</label>
      {% render_field form.name type="text" class="form-control" %}
      {% for error in form.name.errors %}<div class="alert alert-danger">{{ error }}</div>{% endfor %}
      <br>
      <label for="{{ form.description.id_for_label }}">Описание:</label>
      <br>
      {% render_field form.description type="text" class="form-control" %}
      {% for error in form.description.errors %}<div class="alert alert-danger">{{ error }}</div>{% endfor %}
      <br>
      <label for="{{ form.image.id_for_label }}">Изображение:</label>
      {% render_field form.image class="form-control" %}
      <br>
      <label for="{{ form.price.id_for_label }}">Цена:</label>
      {% render_field form.price type="number" class="form-control" %}
      <br>
      <label for="{{ form.is_published.id_for_label }}">{{ form.is_published.label }}</label>
      {% render_field form.is_published type="checkbox" class="form-check-inline" %}
      <br>
      <br>
      <button type="submit" class="btn btn-warning">Сохранить</button>
    </form>
  </div>
{% endblock content %}

apps/catalog/templates/catalog/product_list.html
{% extends "catalog/base.html" %}

{% block content %}
  <div class="container">
    <h1>Каталог</h1>
    <div class="row">
      {% if product_list %}
        {% for product in product_list %}
          {% include "catalog/includes/card.html" with product=product %}
        {% endfor %}
      {% endif %}
    </div>
    {% if user.is_authenticated %}
      <div class="btn-float w-auto">
        <a href="{% url 'catalog:product_form' %}"
           class="btn btn-warning btn-lg rounded-circle">+</a>
      </div>
    {% endif %}
  </div>
{% endblock content %}

apps/catalog/templates/catalog/version_form.html
{% extends 'catalog/base.html' %}
{% load widget_tweaks %}
{% block content %}

    <div class="container text-center mt-5">
        <h1>Добавить версию</h1>
        <br>
        <form method="post">
            {% csrf_token %}
            <label for="{{ form.name.id_for_label }}">Название версии:</label>
            {% render_field form.name type="text" class="form-control" %}
            <br>
            <label for="{{ form.number.id_for_label }}">Номер версии:</label>
            {% render_field form.number type="number" class="form-control" %}
            {% for error in form.number.errors %}<div class="alert alert-danger">{{ error }}</div>{% endfor %}
            <br>
            <label for="{{ form.is_current.id_for_label }}">Активная версия:</label>
            {% render_field form.is_current type="checkbox" class="form-check-inline" %}
            <br>
            <br>
            <button type="submit" class="btn btn-warning">Сохранить</button>
        </form>
    </div>

{% endblock content %}

apps/catalog/templates/catalog/version_list.html
{% extends 'catalog/base.html' %}
{% load static %}

{% block content %}
    <div class="container mt-3">
        {% if version_list %}
            {% for version in version_list %}
                <div class="col-4 border {% if version.is_current %}border-warning{% endif %} rounded-3 mb-3 p-3">
                    <p>Версия № {{ version.number }}: {{ version.name }}</p>
                    <div class="d-flex gap-2">
                        <form action="{% url 'catalog:version_toggle' pk=version.pk %}"
                              method="post">
                            {% csrf_token %}
                            <label for="{{ version.pk }}">Версия:</label>
                            {% if version.is_current %}
                                <a href="{% url 'catalog:version_toggle' pk=version.pk %}"
                                   class="btn btn-warning">Активная</a>
                            {% else %}
                                <a href="{% url 'catalog:version_toggle' pk=version.pk %}"
                                   class="btn btn-dark">Не активная</a>
                            {% endif %}
                        </form>
                        <form action="{% url 'catalog:version_delete' pk=version.pk %}"
                              method="post">
                            {% csrf_token %}
                            <button class="btn btn-danger" type="submit">
                                <img src="{% static 'icons/trash3-fill.svg' %}" alt="trash">
                            </button>
                        </form>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
        <a href="{% url 'catalog:version_form' product_pk=product_pk %}"
           class="btn btn-warning">Добавить</a>
        <br>
        <br>
        <a href="{% url 'catalog:product_detail' pk=product_pk %}"
           class="btn btn-warning">Назад</a>
    </div>
{% endblock content %}