apps/posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('create/', views.PostCreateView.as_view(), name='post_form'),
    path('detail/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='post_update'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='post_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('apps.catalog.urls', namespace='catalog')),
    path('posts/', include('apps.posts.urls', namespace='posts')),
    path('users/', include('apps.users.urls', namespace='users')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/posts/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from apps.catalog.models import BaseModel
# Create your models here.


class Post(BaseModel):
    title = models.CharField(max_length=255, verbose_name=_('Заголовок'))
    slug = models.CharField(max_length=255, verbose_name='slug')
    text = models.TextField(verbose_name=_('Текст'))
    preview = models.ImageField(upload_to='posts/', verbose_name=_('Превью'), blank=True, null=True)
    is_published = models.BooleanField(default=False, verbose_name=_('Опубликовано'))
    views_count = models.IntegerField(default=0, verbose_name=_('Количество просмотров'))

    class Meta:
        verbose_name = _('Пост')
        verbose_name_plural = _('Посты')

    def __str__(self):
        return self.title

apps/posts/views.py
from django.urls import reverse, reverse_lazy
from django.views import generic
from pytils.translit import slugify
from .models import Post


class PostListView(generic.ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(is_published=True)


class PostCreateView(generic.CreateView):
    model = Post
    fields = ('title', 'text', 'preview', 'is_published', )
    success_url = reverse_lazy('posts:post_list')

    def form_valid(self, form):
        form.instance.slug = slugify(form.instance.title)
        form.save()
        return super().form_valid(form)


class PostDetailView(generic.DetailView):
    model = Post

    def get_object(self, queryset=None):
        obj_ = super().get_object(queryset)
        obj_.views_count += 1
        obj_.save()
        return obj_


class PostUpdateView(generic.UpdateView):
    model = Post
    fields = ('title', 'text', 'preview', 'is_published', )

    def get_success_url(self) -> str:
        return reverse('posts:post_detail', kwargs={'pk': self.object.pk})


class PostDeleteView(generic.DeleteView):
    model = Post
    success_url = reverse_lazy('posts:post_list')

apps/posts/templates/posts/includes/card.html
<div class="col-12">
    <div class="card mb-4">
        <div class="card-body">
            <div class="card-title d-flex justify-content-between">
                <h5 class="text-truncate">{{ post.title }}</h5>
                {% if post.preview %}
                    <img src="{{ post.preview.url }}"
                         class="card-img-top img-fluid"
                         style="height: 150px;
                                width: 100px"
                         alt="{{ post.title }}" />
                {% endif %}
            </div>
            <div class="d-flex gap-2">
                <p class="card-text text-truncate">Количество просмотров: {{ post.views_count }} /</p>
                <p class="card-text text-truncate">Дата публикации: {{ post.created_at }} /</p>
                <p class="card-text text-truncate">Дата последнего редактирования: {{ post.updated_at }}</p>
            </div>
            
            <div class="d-flex gap-2">
                <a href="{% url 'posts:post_detail' pk=post.pk %}"
                   class="btn btn-warning">Открыть</a>
                <a href="{% url 'posts:post_update' pk=post.pk %}" class="btn btn-info">Редактировать</a>
                <form method="post" action="{% url 'posts:post_delete' pk=post.pk %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Удалить</button>
                </form>
            </div>
        </div>
    </div>
</div>