apps/catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views


app_name = 'catalog'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='product_list'),

    path('categories/', views.CategoryListView.as_view(), name='category_list'),
    
    path('product/create/', views.ProductCreateView.as_view(), name='product_form'),
    path('product/<int:pk>/', cache_page(60)(views.ProductDetailView.as_view()), name='product_detail'),
    path('product/update/<int:pk>/', views.ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', views.ProductDeleteView.as_view(), name='product_delete'),

    path('product/<int:product_pk>/versions/', views.VersionListView.as_view(), name='version_list'),
    path('product/<int:product_pk>/versions/create/', views.VersionCreateView.as_view(), name='version_form'),
    path('versions/delete/<int:pk>/', views.VersionDeleteView.as_view(), name='version_delete'),
    path('versions/toggle_current/<int:pk>/', views.toggle_current_version, name='version_toggle'),

    path('feedback/', views.FeedbackView.as_view(), name='feedback'),
]

apps/posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('create/', views.PostCreateView.as_view(), name='post_form'),
    path('detail/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='post_update'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='post_delete'),
]

apps/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('email-verification/<email>/', views.email_verification, name='email-verification'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='reset-password'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('apps.catalog.urls', namespace='catalog')),
    path('posts/', include('apps.posts.urls', namespace='posts')),
    path('users/', include('apps.users.urls', namespace='users')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/catalog/models/basemodel.py
from django.db import models


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

apps/catalog/models/category.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from .basemodel import BaseModel


class Category(BaseModel):
    name = models.CharField(max_length=255, verbose_name=_('Название'))
    description = models.TextField(blank=True, verbose_name=_('Описание'))

    class Meta:
        verbose_name = _('Категория')
        verbose_name_plural = _('Категории')

    def __str__(self):
        return self.name

apps/catalog/models/censor.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from .basemodel import BaseModel


class Censor(BaseModel):
    word = models.CharField(max_length=255, verbose_name=_('Слово'))

    def __str__(self):
        return self.word

    class Meta:
        verbose_name = _('Цензура')
        verbose_name_plural = _('Цензура')

apps/catalog/models/product.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from .basemodel import BaseModel


class Product(BaseModel):
    user = models.ForeignKey('users.User', on_delete=models.CASCADE, verbose_name=_('Пользователь'), related_name='products')
    name = models.CharField(max_length=255, verbose_name=_('Название'))
    description = models.TextField(blank=True, verbose_name=_('Описание'))
    image = models.ImageField(upload_to='products/', blank=True, null=True, verbose_name=_('Изображение'))
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name=_('Категория'))
    price = models.FloatField(verbose_name=_('Цена'))
    is_published = models.BooleanField(default=False, verbose_name=_('Опубликовано'))

    class Meta:
        verbose_name = _('Продукт')
        verbose_name_plural = _('Продукты')
        permissions = [
            ("can_change_published", "Can change is_published status"),
            ("can_change_description", "Can change description"),
            ("can_change_category", "Can change category"),
        ]

    def __str__(self):
        return self.name

apps/catalog/models/version.py
from django.db import models
from django.db.models.signals import pre_save, post_delete
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _

from .basemodel import BaseModel


class Version(BaseModel):
    name = models.CharField(max_length=255, verbose_name=_('Название версии'))
    number = models.IntegerField(unique=True, verbose_name=_('Номер версии'))
    is_current = models.BooleanField(default=True, verbose_name=_('Текущая версия'))
    product = models.ForeignKey('Product', on_delete=models.CASCADE, verbose_name=_('Продукт'), related_name='versions')

    class Meta:
        verbose_name = _('Версия продукта')
        verbose_name_plural = _('Версии продукта')
        ordering = ['number']

    def __str__(self):
        return f'{self.number}. {self.name} ({self.is_current})'


@receiver(pre_save, sender=Version)
def pre_save_version(sender, instance, **kwargs):
    Version.objects.filter(product=instance.product, is_current=True).update(is_current=False)


@receiver(post_delete, sender=Version)
def post_delete_version(sender, instance, **kwargs):
    if instance.is_current:
        previous_versions = Version.objects.filter(product__pk=instance.product.pk)
        if previous_versions.exists():
            previous_version = previous_versions.latest('number')
            previous_version.is_current = True
            previous_version.save()

apps/catalog/forms.py
from django import forms
from .models import Product, Censor


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ['name', 'description', 'image', 'category', 'price', 'is_published']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['is_published'].widget.attrs['hidden'] = True
        self.fields['is_published'].label = ''

    def clean_name(self):
        name = self.cleaned_data['name'].lower()
        stop_words = []
        for censured_word in Censor.objects.values_list('word', flat=True):
            if censured_word.lower() in name:
                stop_words.append(censured_word)
        if stop_words:
            raise forms.ValidationError(f'Содержутся запрещенные слова: {', '.join(stop_words)}')
        return name

    def clean_description(self):
        description = self.cleaned_data['description'].lower()
        stop_words = []
        for censured_word in Censor.objects.values_list('word', flat=True):
            if censured_word.lower() in description:
                stop_words.append(censured_word)
        if stop_words:
            raise forms.ValidationError(f'Содержутся запрещенные слова: {', '.join(stop_words)}')
        return description


class ModeratorProductForm(ProductForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].disabled = True
        self.fields['image'].disabled = True
        self.fields['price'].disabled = True
        self.fields['is_published'].widget.attrs['hidden'] = False
        self.fields['is_published'].label = 'Опубликован:'

apps/catalog/views.py
from django.views import generic
from django.urls import reverse_lazy
from django.shortcuts import redirect, render
# Create your views here.

from .forms import ProductForm
from .models import Product, Version


class ProductListView(generic.ListView):
    model = Product


class ProductCreateView(generic.CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')


class ProductDetailView(generic.DetailView):
    model = Product


class ProductDeleteView(generic.DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:product_list')


class FeedbackView(generic.View):

    def get(self, request):
        return render(request, 'catalog/feedback.html')

    def post(self, request):
        return redirect('catalog:product_list')

apps/catalog/views/categories.py
from django.views import generic

from apps.catalog.models import Category
from apps.catalog.services import get_cached_list_categories


class CategoryListView(generic.ListView):
    model = Category
    queryset = get_cached_list_categories()

apps/catalog/views/feedback.py
from django.views import generic
from django.shortcuts import redirect, render
# Create your views here.


class FeedbackView(generic.View):

    def get(self, request):
        return render(request, 'catalog/feedback.html')

    def post(self, request):
        return redirect('catalog:product_list')

apps/catalog/views/product.py
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

from apps.catalog.models import Product
from apps.catalog.forms import ModeratorProductForm, ProductForm
from apps.users.permissions import EmailVerifiedRequiredMixin


class ProductListView(generic.ListView):
    model = Product


class ProductCreateView(LoginRequiredMixin, EmailVerifiedRequiredMixin, generic.CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')
    login_url = reverse_lazy('users:login')

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        return super().form_valid(form)


class ProductDetailView(LoginRequiredMixin, EmailVerifiedRequiredMixin, generic.DetailView):
    model = Product


class ProductUpdateView(LoginRequiredMixin, EmailVerifiedRequiredMixin, generic.UpdateView):
    model = Product
    success_url = reverse_lazy('catalog:product_list')

    def get_form_class(self):
        if self.request.user.groups.filter(name='moderator').exists():
            return ModeratorProductForm
        return ProductForm


class ProductDeleteView(LoginRequiredMixin, EmailVerifiedRequiredMixin, generic.DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:product_list')

apps/catalog/views/version.py
from django.views import generic
from django.urls import reverse
from django.shortcuts import redirect

from apps.catalog.models import Product, Version


class VersionListView(generic.ListView):
    model = Version

    def get_queryset(self):
        return Version.objects.filter(product__pk=self.kwargs['product_pk'])

    def get_context_data(self, **kwargs):
        return super().get_context_data(product_pk=self.kwargs['product_pk'], **kwargs)


class VersionCreateView(generic.CreateView):
    model = Version
    fields = ('name', 'number', 'is_current')

    def form_valid(self, form):
        form.instance.product = Product.objects.get(pk=self.kwargs['product_pk'])
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('catalog:version_list', kwargs={'product_pk': self.kwargs['product_pk']})


class VersionDeleteView(generic.DeleteView):
    model = Version

    def get_success_url(self):
        return reverse('catalog:version_list', kwargs={'product_pk': self.object.product.pk})


def toggle_current_version(request, pk):
    version = Version.objects.get(pk=pk)
    version.is_current = not version.is_current
    version.save()
    return redirect('catalog:version_list', product_pk=version.product.pk)

apps/catalog/templates/catalog/includes/card.html
{% load static %}
{% load custom_tags %}

<div class="col-xxl-3 col-xl-4 col-lg-4 col-md-6 col-sm-12 mb-2">
  <div class="card" style="width: 18rem;">
    <img src="{{ product|img_url }}"
         class="card-img-top"
         alt="{{ product.name }}"
         height="400" />
    <div class="card-body">
      <div class="card-title d-flex justify-content-between">
        <h5 class="text-truncate">{{ product.name }} {{ product|current_version_name }}</h5>
        <h5>{{ product.price|floatformat }}₽</h5>
      </div>
      <p class="card-text text-truncate">{{ product.description }}</p>
      <div class="card-title d-flex justify-content-between">
        <a href="{% url 'catalog:product_detail' pk=product.pk %}"
           class="btn btn-warning">Открыть</a>
        {% if request.user == product.user or perms.catalog.can_change_published %}
          <a href="{% url 'catalog:product_update' pk=product.pk %}"
             class="btn btn-warning">Изменить</a>
        {% endif %}
        <form method="post"
              action="{% url 'catalog:product_delete' pk=product.pk %}">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger">
            <img src="{% static 'icons/trash3-fill.svg' %}" alt="delete">
          </button>
        </form>
      </div>
    </div>
  </div>
</div>

apps/catalog/templates/catalog/includes/header.html
<nav class="navbar sticky-top navbar-expand-lg bg-body-tertiary">
  <div class="container m-auto my-2">
    <button class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'catalog:product_list' %}">Shoppify</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link"
             aria-current="page"
             href="{% url 'catalog:product_list' %}">Все товары</a>
        </li>
        <li class="nav-item">
          <a class="nav-link"
             aria-current="page"
             href="{% url 'catalog:category_list' %}">Категории</a>
        </li>
        <li class="nav-item">
          <a class="nav-link"
             aria-current="page"
             href="{% url 'posts:post_list' %}">Статьи</a>
        </li>
        <li class="nav-item">
          <a class="nav-link"
             aria-current="page"
             href="{% url 'catalog:feedback' %}">Контакты</a>
        </li>
      </ul>
    </div>
    <div>
      {% if request.user.is_authenticated %}
        <form action="{% url 'users:logout' %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn btn-warning">Выйти</button>
        </form>
      {% else %}
        <a href="{% url 'users:login' %}" class="btn btn-warning">Войти</a>
        <a href="{% url 'users:register' %}" class="btn btn-warning">Регистрация</a>
      {% endif %}
    </div>
  </div>
</nav>